### PR TITLE
Add a Travis step to push a combined Docker image

### PR DESCRIPTION
**Pull request by hufman**
I _think_ this would work, I'm not quite sure if the second deploy step will wait until the first deploy step is finished across the job matrix.

### CODE REVIEW

**Comment by EugenMayer** [comment]
Well it's a build failing due to a missing patch, i assume this is now also broken on master, let's see, i started a job https://app.travis-ci.com/github/EugenMayer/docker-image-unison/builds/254897422 - so it might be just regression

**Comment by EugenMayer** [comment]
It is most probably this patch https://github.com/EugenMayer/docker-image-unison/blob/master/Dockerfile#L32 which is only applied for specific unison versions.

Interestingly removing the patch file fails, and since the patch is downloaded for all version.

Since i'am not using any of this for a lone time now, i'am currently not willing to put any time into this. I would encourage you to try to fix it and create a PR for fixing the current build issues. The we merge it, then we go downstream here and this PR should then be good to go.

I will try to review PRs and play rubber duck, but the actual work needs to be done by a contributor right now, sorry. 

Tracking the master build issue on https://github.com/EugenMayer/docker-image-unison/issues/30

**Comment by blackjid** [comment]
I've tried building using newer versions of ocaml and unison, and it build ok, and looks like it is working fine..
```
ARG OCAML_VERSION=4.14.0
ARG UNISON_VERSION=2.52.1
```

Is there any hard dependency on the older versions?

**Comment by EugenMayer** [comment]
supeseeded by #31

**Pull request closed without merging**
