### PR TITLE
Add Travis step for combined image & Update unison version fixes #27 #30

### LINKED ISSUE #27: Push a combined amd64+arm64 Docker tag
Thank you for this incredible Unison Docker image, which is the most popular Unison image on Dockerhub by a staggering amount!
Docker recently gained the ability to [build a combined image manifest](https://www.docker.com/blog/multi-arch-build-and-images-the-simple-way/) to include multiple platforms within the same image tag. Can this be provided with the Unison image? I believe the following commands should do the trick:
```
docker manifest create eugenmayer/unison:2.51.3-4.12.0 eugenmayer/unison:2.51.3-4.12.0-AMD64 eugenmayer/unison:2.51.3-4.12.0-ARM64
docker manifest create eugenmayer/unison:latest eugenmayer/unison:2.51.3-4.12.0-AMD64 eugenmayer/unison:2.51.3-4.12.0-ARM64
docker manifest push eugenmayer/unison:2.51.3-4.12.0
docker manifest push eugenmayer/unison:latest
```

I've tested these steps with a [test upload](https://hub.docker.com/repository/docker/hufman/unison/tags), if you'd like to see what it looks like on Docker Hub.

### PR DESCRIPTION
**Pull request by yosephsa**
Travis step addition thanks to [hufman](https://github.com/hufman)
Update unison version to match brew defaults and move to latest supported version

### CODE REVIEW

**Comment by EugenMayer** [comment]
Still failing tests, actually the same issue. Looks like we still build rc2 - didnt you want to stop build that version? Thank you for your effort!

**Comment by yosephsa** [comment]
@EugenMayer I don’t see those versions in the repository, makes me think it’s an environment variable loaded into the Travis build. Do you have any idea where that’s coming from?

**Comment by EugenMayer** [comment]
It's part of the travis configuration https://github.com/EugenMayer/docker-image-unison/blob/master/.travis.yml#L10

**Comment by yosephsa** [comment]
@EugenMayer Thanks, looks like it's working now.
I also removed the ocaml patch from the Dockerfile since we are using a newer version of unison that doesn't require it.

**Comment by EugenMayer** [comment]
i would say this looks fairly good already, thank you for your work.

One question has yet been unanswered - the unixon version matching.

The question tight now is, what unison are the current 2 macOS versions installing when installing unison locally. This is less important when we use native_osx with docker sync, but important when the unison strategy is used.

AFAICs https://formulae.brew.sh/formula/unison we have ocalm 4.12.0 and according to https://formulae.brew.sh/api/formula/unison.json unison 2.52.1 so the exact version you are compiling with. This looks good.

**Comment by EugenMayer** [comment]
We should also try to sync this changes with adopting

- [ ] https://github.com/EugenMayer/docker-sync/blob/master/lib/docker-sync/sync_strategy/native_osx.rb#L26
- [ ] https://github.com/EugenMayer/docker-sync/blob/master/lib/docker-sync/sync_strategy/unison.rb#L25

While i guess we have to deal with 2 aspects. Adjust the unison version and remove the AMD suffix and since we use the new build mode using the manifests, right?

**Comment by yosephsa** [comment]
@EugenMayer That's right, once we merge this, we can go and create a PR in the docker-sync repository.

The docker-sync repository will not break after this is merged as the older AMD version still exist in docker hub.

Just confirmed, Unison 2.52.1 is the version installed on ARM macOS as well as AMD macOS. Which means that'll match to what is configured in the container in this PR.

**Comment by EugenMayer** [comment]
I guess we are good to go then, i will merge this one. Thank you a lot for the contribution!

**Comment by yosephsa** [comment]
Not a problem, thank you for this great project!

**Comment by yosephsa** [comment]
@EugenMayer We have an issue. Things don't look right on the docker hub page. I only see an ARM tag, looks like the neither the combined tag, not the AMD tag is correct is pushed for some reason.

https://hub.docker.com/r/eugenmayer/unison/tags

**Comment by EugenMayer** [comment]
@yoseph1998 that is not a wonder since the the pushes failed https://github.com/EugenMayer/docker-image-unison/runs/8215332363

The question is, why we run this 2 times https://github.com/EugenMayer/docker-image-unison/blob/master/.travis.yml#L27

The entire setup does not make any sense to me. Run the script once for both arches, and then run it again for AMD64 - while the script creates the manifest for both arches anyway.

**Comment by EugenMayer** [comment]
Trying to fix this. merged combine and push for simplification

**Pull request merged**
