### PR TITLE
Compile Unison with ocaml 4.08.1

### PR DESCRIPTION
**Pull request by JParkinson1991**
Fixes the issues reported here: https://github.com/EugenMayer/docker-sync/issues/687

### CODE REVIEW

**Comment by EugenMayer** [comment]
Thank you for the contribution!

**Comment by JParkinson1991** [comment]
Great, now that this seems to be working with the currently available homebrew version of Unison i wonder is it worth looking at making these host requirments internal?

By that i mean ship a compiled and compatible unison binary within the docker-sync gem for the different operation systems. 

I assume the docker-sync package could use a 'locally' (package local) installed unison instance. Forgive me, not a ruby developer by any means just thinking about ideas in which we can bring more control to host dependencies etc.

**Comment by EugenMayer** [comment]
I understand this would add convinience, but the costs are maintainance and i'am not willing to take that one in since this would require maintaining a custom homebrew tap / bottle for this purpose, which already proven to be a horrible scenario in https://github.com/EugenMayer/homebrew-dockersync

I do neither want to upgrade the taps nor deal with unison in general. It is a dependency and since brew is "one version only" one needs to be careful with upgrades under OSX with projects as bad as unison/unox breaking all day long.

**Comment by JParkinson1991** [comment]
Thats completely understandable. Maybe (most likely) i over simplified in think we could just have the unison stored under the docker-sync package somewhere.

For now it feels the safest option is definitely
```
brew pin unison
brew pin eugenmayer/dockersync/unox
```

**Pull request merged**
