### PR TITLE
Updated binutils version 2.33.1-r0 to 2.34-r0.

### PR DESCRIPTION
**Pull request by safaksaylam**
Docker build error problem fixed.

### CODE REVIEW

**Comment by EugenMayer** [comment]
Thank you - could you give a little more context about your findings? - why should we update them at all?

**Comment by safaksaylam** [comment]
> Thank you - could you give a little more context about your findings? - why should we update them at all?


Docker build command.
```
docker build --build-arg "OCAML_VERSION=4.06.1" --build-arg "UNISON_VERSION=2.51.2" -t custom-docker-image-unison .
```
Result.
```
Sending build context to Docker daemon    170kB
Step 1/16 : FROM alpine:edge
 ---> 24cae4d038c0
Step 2/16 : ARG OCAML_VERSION=4.08.1
 ---> Using cache
 ---> 6ea957621bf4
Step 3/16 : RUN apk update     && apk add --no-cache --virtual .build-deps build-base coreutils 	&& wget http://caml.inria.fr/pub/distrib/ocaml-${OCAML_VERSION:0:4}/ocaml-${OCAML_VERSION}.tar.gz 	&& tar xvf ocaml-${OCAML_VERSION}.tar.gz -C /tmp 	&& cd /tmp/ocaml-${OCAML_VERSION}     && ./configure     && make world     && make opt     && umask 022     && make install     && make clean     && apk del .build-deps  	&& rm -rf /tmp/ocaml-${OCAML_VERSION} 	&& rm /ocaml-${OCAML_VERSION}.tar.gz
 ---> Using cache
 ---> dd332e132d59
Step 4/16 : ARG UNISON_VERSION=2.51.2
 ---> Using cache
 ---> 1afbbcf9379a
Step 5/16 : RUN apk update     && apk add --no-cache --repository="http://dl-cdn.alpinelinux.org/alpine/v3.10/main" binutils=2.33.1-r0     && apk add --no-cache --virtual .build-deps         build-base curl git     && apk add --no-cache         bash inotify-tools monit supervisor rsync ruby     && curl -L https://github.com/bcpierce00/unison/archive/v$UNISON_VERSION.tar.gz | tar zxv -C /tmp     && cd /tmp/unison-${UNISON_VERSION}     && curl https://github.com/bcpierce00/unison/commit/23fa1292.diff?full_index=1 -o patch.diff     && git apply patch.diff     && rm patch.diff     && sed -i -e 's/GLIBC_SUPPORT_INOTIFY 0/GLIBC_SUPPORT_INOTIFY 1/' src/fsmonitor/linux/inotify_stubs.c     && make UISTYLE=text NATIVE=true STATIC=true     && cp src/unison src/unison-fsmonitor /usr/local/bin     && apk del binutils .build-deps      && apk add --no-cache libgcc libstdc++     && rm -rf /tmp/unison-${UNISON_VERSION}     && apk add --no-cache --repository http://dl-4.alpinelinux.org/alpine/edge/testing/ shadow     && apk add --no-cache tzdata
 ---> Running in dc8ebe5953d2
fetch http://dl-cdn.alpinelinux.org/alpine/edge/main/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/edge/community/x86_64/APKINDEX.tar.gz
v20200319-2886-g6e8b358d25 [http://dl-cdn.alpinelinux.org/alpine/edge/main]
v20200319-2885-g9fe12e8611 [http://dl-cdn.alpinelinux.org/alpine/edge/community]
OK: 12518 distinct packages available
fetch http://dl-cdn.alpinelinux.org/alpine/v3.10/main/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/edge/main/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/edge/community/x86_64/APKINDEX.tar.gz
ERROR: unsatisfiable constraints:
  binutils-2.34-r0:
    breaks: world[binutils=2.33.1-r0]
The command '/bin/sh -c apk update     && apk add --no-cache --repository="http://dl-cdn.alpinelinux.org/alpine/v3.10/main" binutils=2.33.1-r0     && apk add --no-cache --virtual .build-deps         build-base curl git     && apk add --no-cache         bash inotify-tools monit supervisor rsync ruby     && curl -L https://github.com/bcpierce00/unison/archive/v$UNISON_VERSION.tar.gz | tar zxv -C /tmp     && cd /tmp/unison-${UNISON_VERSION}     && curl https://github.com/bcpierce00/unison/commit/23fa1292.diff?full_index=1 -o patch.diff     && git apply patch.diff     && rm patch.diff     && sed -i -e 's/GLIBC_SUPPORT_INOTIFY 0/GLIBC_SUPPORT_INOTIFY 1/' src/fsmonitor/linux/inotify_stubs.c     && make UISTYLE=text NATIVE=true STATIC=true     && cp src/unison src/unison-fsmonitor /usr/local/bin     && apk del binutils .build-deps      && apk add --no-cache libgcc libstdc++     && rm -rf /tmp/unison-${UNISON_VERSION}     && apk add --no-cache --repository http://dl-4.alpinelinux.org/alpine/edge/testing/ shadow     && apk add --no-cache tzdata' returned a non-zero code: 1
```

**Comment by ostrolucky** [comment]
Yes, Dockerfile is currently unbuildable, so this should be solved. But I actually fail reason why should we still install specific binutils version. This was introduced in 82b36842bb76b26fb41a6a66901d1e5303642ee3 and it explains that this was in order to be able to compile Unison. However, nowadays Dockerfile builds fine without having this line. Perhaps something you @EugenMayer, or you @JParkinson1991 could clarify?

**Comment by JParkinson1991** [comment]
@ostrolucky if you can get this image to build without errors and without binutils then its probably worth you opening a pull request so that others can test it.

In terms of why the `binutils` dependency was added you're right, this was added so that we could compile specific versions of ocaml to fix issues with homebrew users who had a mismatched version.

Now the reason why i feel like we have to keep updating this dependency is due to the use of `alpine:edge` as the base image. Every time docker is used to build this image it will pull down the latest edge version available, which has its own available version of `binutils` which at this current time is `2.34-r0.` and seems to be updated with each new edge version. 

One approach to fix this to pin the base image used for this one to a specific version, for example `alpine:3.11` that would lock the available version of binutils to `2.33.1-r0` and would stop us having to update the binutils dependency with each new version of alpine. Again, this would need a pull request and testing etc before rolled into a release. @EugenMayer can advise on this.

**Comment by ostrolucky** [comment]
Alright, created https://github.com/EugenMayer/docker-image-unison/pull/14

**Comment by EugenMayer** [comment]
Interesting discussion. The point is, what does binutils mean for ocalm / unison.

Is ocalm compiled against it ( static/dynamic ) and thus the same ocalm version could then still lead to issues on client/server due to different `binutils`?

I have no big issues pinning down the base image in this scenario, so we can go for it without bigger troubles.

So my big questions is, what is the real impact of binutils?

**Comment by ostrolucky** [comment]
I would suggest stop pinning binutils, rather than pinning alpine, like my PR does. It's better to find out early when our setup stops working with modern distributions, rather than later.

**Comment by JParkinson1991** [comment]
I remember having to use that specific version of binutils when trying to compile ocaml in my original change.

If im not mistaken, edge came with its out version that was throwing errors when trying to compile ocaml version 4.08.1. I cant really remember to be honest now, but i know first option wouldnt have been to go for a specific version of bintuls if i didnt have to.

@ostrolucky did you test compilation of ocaml at both 4.08.1 and 4.06.1 in your update Dockerfile?

**Comment by ostrolucky** [comment]
Yes, like I mentioned in PR description Dockerfile build works with that. I was also running unison server with this image for most of the today, didn't see any incompatibility issues.

**Comment by EugenMayer** [comment]
Closing this in favor of #14 - thank you for the work / discussion and PR

**Comment by EugenMayer** [comment]
Ok but AFAICS we already have static linking/binding/compile issues during building the image, not something hidden and incompatible during runtime (so it's not something happens due to dynamic linking) - thus i would also either not pin anything (it's not like we are rebuilding the image non-stop using CI atm) - i would though just comment the pinning out if we once need it again to bridge incompatibilities (for a time slice).

**Pull request closed without merging**
